#### general settings
name: EDB
use_tb_logger: true
model: denoising
distortion: sr
gpu_ids: [0]

sde:
  T: 100
  eps: 0.005

degradation: 
  noise_type: G
  scale: 4
  # scale: 8
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/EDB/icme_code/datasets/DIV2K/DIV2K_train_HR
    dataroot_LQ: /home/EDB/icme_code/datasets/DIV2K/DIV2K_train_LR_bicubic/X4
    # dataroot_GT: /home/EDB/icme_code/datasets/FFHQ
    # dataroot_LQ: /home/EDB/icme_code/datasets/FFHQ/X4

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4
    GT_size: 128
    LR_size: 32
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/EDB/icme_code/datasets/DIV2K/DIV2K_valid_HR
    dataroot_LQ: /home/EDB/icme_code/datasets/DIV2K/DIV2K_valid_LR_bicubic/X4
    # dataroot_GT: /home/EDB/icme_code/datasets/celebahq
    # dataroot_LQ: /home/EDB/icme_code/datasets/celebahq/X4
    GT_size: 128
    LR_size: 32


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
